services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zedelivery

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ze_delivery
    ports:
      - 8000:8000
    env_file:
      - .env_files/.env.dev

volumes:
  postgres_data:
